Update install docs with upgrade management section
canonical/microceph pull request #101
Opened 2023-03-15 20:42 UTC by lmlg

This PR adds a section in the installation docs that specifies the recommended way to manage upgrades.

2023-03-16 14:15 UTC, ChrisMacNaughton requested changes

2023-03-16 14:15 UTC, ChrisMacNaughton commented on docs/tutorial/install.rst
> +For the time being, it's recommended that updates be postponed indefinitely.
This isn't a 'for the time being' thing, it's a 'this is how we recommend you install and manage the lifecycle of microceph. Fundamentally, we're never going to be able to manage microceph updates from within microceph so we have to recommend the correct workflows for our users to manage it themselves and that includes holding the version, as well as how to update when they're ready!

2023-03-21 04:44 UTC, wolsen requested changes

2023-03-21 04:44 UTC, wolsen commented on docs/tutorial/install.rst
> +        lxc exec microceph-$i -- sh -c 'snap refresh --hold microceph'
This command is specific to running micro ceph in a lxd container. You should simply state that the snap refresh --hold command is the correct command. The example can reference to running within a lxd container, but a baremetal machine wouldn't use the lxc part of the command.

2023-03-22 12:41 UTC, ChrisMacNaughton requested changes

2023-03-22 12:41 UTC, ChrisMacNaughton commented on docs/tutorial/update.rst
> +    snap install microceph
I believe that this will do nothing?

I suspect we want something like:

```
snap refresh microceph
snap refresh --hold microceph
```

2023-03-23 09:41 UTC, sabaini requested changes
Hey, thanks for the instructions, added some comments inline

2023-03-23 09:41 UTC, sabaini commented on docs/tutorial/update.rst
> +Microceph will not manages its own updates - users are required to do so. In order to set up microceph to manage updates correctly, the following steps need to be taken.
I feel like users who are not familiar with snaps would benefit from some context around snap updates. Also, I don't think we should make it an imperative -- a single node MicroCeph cluster should be fine with auto-upgrades (if the upgrade works at all). Maybe something like:

----

MicroCeph updates are managed by the snap mechanisms. By default snaps will automatically deploy updates, this however can be problematic for MicroCeph clusters due to ordering of and concurrent rollout of updates. It's therefore strongly advised to disable automatic updates for MicroCeph snaps. For details on the snap update mechanism look [here](https://snapcraft.io/docs/keeping-snaps-up-to-date)

----

2023-03-23 09:41 UTC, sabaini commented on docs/tutorial/update.rst
> +    snap refresh --hold microceph
Will need sudo
`sudo snap refresh --hold microceph`

2023-03-23 09:41 UTC, sabaini commented on docs/tutorial/update.rst
> +    snap refresh --hold microceph
Will need sudo

2023-03-23 09:41 UTC, sabaini commented on docs/tutorial/update.rst
> +With that done, we should verify the cluster together to make it's settled and healthy once again.
Maybe add, for version verification:

```
.. code-block:: shell
    snap list microceph
```


Maybe this again for health verification
```
.. code-block:: shell
    microceph.ceph status
```

2023-03-24 08:49 UTC, sabaini requested changes
Looking good! 
Noted two typos and a very minor suggestion

2023-03-24 08:49 UTC, sabaini commented on docs/tutorial/update.rst
> +As such, we strongly advise that automatic updates be disabled for Microceph. Documentation about snaps updates can be consulted `here <https://snapcraft.io/docs/keeping-snaps-up-to-date>`_.
s/snaps updates/snap updates/

2023-03-24 08:49 UTC, sabaini commented on docs/tutorial/update.rst
> +The order on which we run the commands is important. It should be as follows:
s/order on/order in/

2023-03-24 08:49 UTC, sabaini commented on docs/tutorial/update.rst
> +1. Managers
Just for extra foolproof-ness maybe:

1. Managers (mgr)
2. Monitors (mon)
3. All other entities (OSDs, rgw, etc.)

2023-04-21 09:39 UTC, ChrisMacNaughton commented
One thing that I don't see in this proposal is that we should include the `snap refresh --hold microceph` in the install documentation as well, or people will only discover this outage=inducing behaviour at upgrade time (or outage time!), rather than at install time!

2023-04-24 17:02 UTC, sabaini commented
One of the checks shows a warning -- update.rst is not being referenced by any TOC. Which is a fair point I guess, we'll want it to be included in the index probably?

2023-04-25 09:02 UTC, merged