Adds HACKING.md for newbies
canonical/microceph pull request #156
Opened 2023-07-10 12:26 UTC by UtkarshBhatthere

2023-07-10 16:26 UTC, sabaini requested changes
Hey, thanks for this, looks very nice.

One general naming suggestion on MicroCeph vs. microceph which comes up in several places. To lessen the confusion around CamelCase vs lowercase in naming IMHO we almost always should refer to MicroCeph (as in the MicroCeph product), and only refer to the lowercase microceph when we are specifically talking about the built microceph snap
file, or `microceph` subdirs or similar.

Some typo nits inline.

2023-07-10 16:26 UTC, sabaini commented on HACKING.md
> +The microceph codebase resides inside the microceph sub-directory of the repo. This subdir is neatly organised into parts which make up the whole of microceph. Below is a brief description of what ca
s/rederence/reference/

2023-07-10 16:26 UTC, sabaini commented on HACKING.md
> +    Contains files which directly related to ceph orchestration. This includes code for ceph cluster configuration, service orchestration etc.
s/which directly/which are directly/

2023-07-10 16:26 UTC, sabaini commented on HACKING.md
> +    Contains mock definitions for Unit Testing
s/Unit Testing/unit testing/

2023-07-10 16:26 UTC, sabaini commented on HACKING.md
> +The microceph [makefile](/microceph/Makefile) has targets for running Unit Tests and Lint checks. They can be run as follows.
s/Unit Testing/unit testing/
s/Lint/lint/

2023-07-11 04:34 UTC, UtkarshBhatthere commented on HACKING.md
> +Hold your horses, no-one's hacking anything. The aim of this document is to enable new developers/users get familiarised with the build tools and codebase of microceph so that they can build and cont
Aaaah, the good hackers :D.. Ack

2023-07-11 04:38 UTC, UtkarshBhatthere commented on HACKING.md
> +Apart from being a self dependant artifact, being a snap enables Microceph to be isolated from host and provide a clean and consistent building, installing and cleanup experience.
Ack

2023-07-11 04:38 UTC, UtkarshBhatthere commented on HACKING.md
> +The microceph codebase resides inside the microceph sub-directory of the repo. This subdir is neatly organised into parts which make up the whole of microceph. Below is a brief description of what ca
Nice Catch :D

2023-07-11 04:39 UTC, UtkarshBhatthere commented on HACKING.md
> +    Contains files which directly related to ceph orchestration. This includes code for ceph cluster configuration, service orchestration etc.
Ack

2023-07-11 04:39 UTC, UtkarshBhatthere commented on HACKING.md
> +The microceph [makefile](/microceph/Makefile) has targets for running Unit Tests and Lint checks. They can be run as follows.
ack

2023-07-11 04:39 UTC, UtkarshBhatthere commented on HACKING.md
> +    Contains mock definitions for Unit Testing
ack

2023-07-11 12:35 UTC, sabaini approved these changes

2023-07-11 12:35 UTC, merged