Added documentation for Ceph-Dashboard enablement
canonical/microceph pull request #184
Opened 2023-08-16 13:14 UTC by UtkarshBhatthere

Added docs for enabling ceph-dashboard and integrating it with Prometheus and Alertmanager.

2023-08-16 14:24 UTC, nobuto-m commented
What about Grafana integration? Also, what about HA of Ceph Dashboard? Do we have a single and highly available entry point to access the dashboard?

2023-08-17 08:04 UTC, UtkarshBhatthere commented
> What about Grafana integration? Also, what about HA of Ceph Dashboard? Do we have a single and highly available entry point to access the dashboard?

Hey @nobuto-m ! I am happy to see that you are excited about MicroCeph. We don't have ceph-dashboard HA available or in plans right now. I will raise this in ceph team discussions so that we seed it into our active backlog. About grafana, I will go ahead and add that documentation to the MicroCeph docs as well.

2023-08-17 08:10 UTC, sabaini requested changes
Lgtm in general, found a typo and added a suggestion

2023-08-17 08:10 UTC, sabaini commented on docs/tutorial/enable_dashboard.rst
> +Ceph-Dashboard is a built-in web based application for monitoring and management of your Ceph cluster. This makes it easy for administer Ceph clusters for users who prefer WebUI over CLI. It is imple
Typos, should be "easy to administer"

2023-08-17 08:10 UTC, sabaini commented on docs/tutorial/enable_dashboard.rst
> +  Ceph Dashboard: Monitoring
Suggest some closing phrase, e.g.: 

> As an example, this shows details of a CephHealthWarning

2023-08-17 08:25 UTC, UtkarshBhatthere commented on docs/tutorial/enable_dashboard.rst
> +  Ceph Dashboard: Monitoring
Ack

2023-08-24 09:40 UTC, merged