Add single-node tutorial
canonical/microceph pull request #200
Opened 2023-08-30 22:32 UTC by pmatulis

Leave this new tutorial hidden in the navigation for now. After the addition of another tutorial in a second PR the old tutorial material will be unpublished in a third PR.

2023-08-30 22:48 UTC, pmatulis commented
@utkarsh2102 Can you advise on the failed CI test?

2023-08-31 08:37 UTC, sabaini requested changes
Hi, left some inline commentary. Thanks!

2023-08-31 08:37 UTC, sabaini commented on docs/tutorial-2/single-node.rst
> +Rechcek status:
Typo: "Recheck"

2023-08-31 08:37 UTC, sabaini commented on docs/tutorial-2/single-node.rst
> +The output should now show three disks and the additional presense of the OSD
Typo: "presence"

2023-08-31 08:37 UTC, sabaini commented on docs/tutorial-2/single-node.rst
> +``/dev/sdb``, and ``/dev/sdc``.
Not sure if it goes without saying, but might want to add a caution that we're going to wipe the data? Either here or below when actually adding the disks

2023-08-31 08:37 UTC, sabaini commented on docs/tutorial-2/single-node.rst
> +
I wonder if we may want to show the output of `ceph -s` as well to demonstrate we now have a full, healthy ceph cluster

2023-09-01 08:33 UTC, sabaini approved these changes
lgtm, cheers

2023-09-01 08:44 UTC, merged