Support OSD file backing
canonical/microceph pull request #261
Opened 2023-11-20 18:12 UTC by sabaini

Add support for auto-creating loopback backing for OSDs

2023-11-22 09:51 UTC, UtkarshBhatthere requested changes
Did a very quick review, LGTM in general, just a small nit and the CLI changes seem missing ?

2023-11-22 09:51 UTC, UtkarshBhatthere commented on microceph/ceph/osd.go
> +	if match != nil {
This is slightly different from the function structure which is (usually)"
```
if ERR {
    # RETURN ERROR
}

# PROCEED
```

but rather:
```
if SUCCESS {
    # Core Logic
}
# Return Error
```

The only nit being the structure is unconventional for quick reading.

2023-11-22 11:10 UTC, sabaini commented
> Did a very quick review, LGTM in general, just a small nit and the CLI changes seem missing ?

Thanks! I've now added longer help text for clarity

2023-11-23 11:19 UTC, sabaini commented on microceph/ceph/osd.go
> +	switch strings.ToUpper(unit) {
The regexp should take care of that -- it matches only M, G or T. Anything else won't match and cause an "illegal spec" error

2023-11-23 11:21 UTC, sabaini commented on microceph/ceph/osd.go
> +	// sanity: loopback file and WAL/DB are mutually exclusive
My reasoning was that having loop files and using separate WAL/DB devices are orthogonal use cases, and we'd complicate implementation but also user interface surface without much benefit

2023-11-23 17:26 UTC, merged