Added json output flag to Disk List
canonical/microceph pull request #295
Opened 2024-02-07 10:00 UTC by UtkarshBhatthere

```
$ sudo microceph disk list --json
{"ConfiguredDisks":[{"osd":1,"path":"/dev/loop5","location":"juju-3b5009-0"}],"UnpartitionedDisks":[]}
```

2024-02-07 10:14 UTC, sabaini requested changes
Hey, lgtm in general!
It would be great if we could have a test (either unit or functional) for this though

2024-02-07 10:29 UTC, UtkarshBhatthere commented
Ack @sabaini, will add a UT.

2024-02-08 08:29 UTC, sabaini requested changes
Hey, one small typo in an error message, otherwise lgtm
Just a note for future reference on commit structure, it would be preferable from a to keep commits focused. The last commit message here describes adding a functional test, it does a bit more than that though :-)

2024-02-08 08:29 UTC, sabaini commented on microceph/cmd/microceph/init.go
> +		return fmt.Errorf("internal error: unable to fetch unpartitoned disks: %w", err)
typo: "unpartitioned"

2024-02-08 10:46 UTC, UtkarshBhatthere commented on microceph/cmd/microceph/init.go
> +		return fmt.Errorf("internal error: unable to fetch unpartitoned disks: %w", err)
ack

2024-02-08 10:49 UTC, UtkarshBhatthere commented
@sabaini note taken! 😄

2024-02-08 11:02 UTC, sabaini approved these changes
cheers

2024-02-08 11:03 UTC, merged