Document the 'pool/set-rf' command
canonical/microceph pull request #331
Opened 2024-03-22 19:37 UTC by lmlg

2024-03-22 22:12 UTC, MggMuggins requested changes

2024-03-22 22:12 UTC, MggMuggins commented on docs/reference/commands/pool.rst
> +   set-tf      Set the replication factor for pools
Typo?

2024-03-26 05:01 UTC, UtkarshBhatthere approved these changes

2024-03-26 05:02 UTC, UtkarshBhatthere commented on docs/reference/commands/pool.rst
> +   microceph disk [command]
incorrect command.

2024-03-26 05:03 UTC, UtkarshBhatthere requested changes
one change needed.

2024-03-26 15:08 UTC, UtkarshBhatthere approved these changes
LGTM

2024-03-26 15:12 UTC, merged